events {}

http {
    # Ces URLs sont les URLs publiques des services Railway
    upstream auth_service {
        server hotel-booking-platform-production.up.railway.app:443;
    }
    upstream hotel_service {
        server natural-surprise-production-a613.up.railway.app:443;
    }
    upstream booking_service {
        server booking-service-production-a38a.up.railway.app:443;
    }
    upstream chat_service {
        server chat-service-production-eeb1.up.railway.app:443;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass https://auth_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
        }

        location = /api/hotels {
            proxy_pass https://hotel_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
        }

        location /api/hotels/ {
            proxy_pass https://hotel_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
            client_max_body_size 10M;
        }

        location = /api/rooms {
            proxy_pass https://hotel_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
        }

        location /api/rooms/ {
            proxy_pass https://hotel_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
            client_max_body_size 10M;
        }

        location /storage/ {
            proxy_pass https://hotel_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
            client_max_body_size 10M;
        }

        location = /api/bookings {
            proxy_pass https://booking_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
        }

        location /api/bookings/ {
            proxy_pass https://booking_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
        }

        location /api/chat/ {
            proxy_pass https://chat_service;
            proxy_set_header Host $host;
            proxy_ssl_server_name on;
        }

        location / {
            return 404 "Route API inconnue\n";
        }
    }
}